package km222pw_assign3.NorseGodsFile;

import java.util.ArrayList;

public class NorseGods_Info {
    public  ArrayList<NorseGods> norseGodsArrayList() {
        ArrayList<NorseGods> godsArrayList = new ArrayList<>();
        godsArrayList.add(new NorseGods("Odin", "Allfather of the Aesir. (Aesir)", "Odin also called Wodan, Woden, or Wotan, one of the principal gods in Norse mythology." +
                " His exact nature and role, however, are difficult to determine because of the complex picture of him given by the wealth of archaeological and literary sources. " +
                "The Roman historian Tacitus stated that the Teutons worshiped Mercury; and because dies Mercurii (“Mercury’s day”) was identified with Wednesday (“Woden’s day”), there is little doubt that the god Woden (the earlier form of Odin) was meant. " +
                "Though Woden was worshiped preeminently, there is not sufficient evidence of his cult to show whether it was practiced by all the Teutonic tribes or to enable conclusions to be drawn about the nature of the god." +
                " Later literary sources, however, indicate that at the end of the pre-Christian period Odin was the principal god in Scandinavia. " +
                "From earliest times Odin was a war god, and he appeared in heroic literature as the protector of heroes; fallen warriors joined him in Valhalla. The wolf and the raven were dedicated to him. His magical horse, Sleipnir, had eight legs, teeth inscribed with runes, and the ability to gallop through the air and over the sea. Odin was the great magician among the gods and was associated with runes. He was also the god of poets. In outward appearance he was a tall, old man, with flowing beard and only one eye (the other he gave in exchange for wisdom). " +
                "He was usually depicted wearing a cloak and a wide-brimmed hat and carrying a spear."));

        godsArrayList.add(new NorseGods("Thor", "God of thunder (Aesir)", "Thor is one of the most prominent figures in Norse mythology. He was a major god of all branches of the Germanic peoples before their conversion to Christianity, although he reached the height of his popularity among the Scandinavians of the late Viking Age." +
                "The Warrior God Par Excellence\n" +
                
                "Thor, the brawny thunder god, is the archetype of a loyal and honorable warrior, the ideal toward which the average human warrior aspired. He’s the indefatigable defender of the Aesir gods and their fortress, Asgard, from the encroachments of the giants, who are usually (although far from invariably) the enemies of the gods.\n" +
                
                "No one is better suited for this task than Thor. His courage and sense of duty are unshakeable, and his physical strength is virtually unmatched. He even owns an unnamed belt of strength (Old Norse megingjarðar) that makes his power doubly formidable when he wears the belt. His most famous possession, however, is his hammer, Mjöllnir (“Lightning”[2]). Only rarely does he go anywhere without it. For the heathen Scandinavians, just as thunder was the embodiment of Thor, lightning was the embodiment of his hammer slaying giants as he rode across the sky in his goat-drawn chariot. (Of course, they didn’t believe he physically rode in a chariot drawn by goats – like everything else in Germanic mythology, this is a symbol used to express an invisible reality upon which the material world is perceived to be patterned.)\n" +
                
                "Thor’s particular enemy is Jormungand, the enormous sea serpent who encircles Midgard, the world of human civilization. In one myth, he tries to pull Jormungand out of the ocean while on a fishing trip, and is stopped only when his giant companion cuts the fishing line out of fear. Thor and Jormungand finally face each other during Ragnarok, however, when the two put an end to each other.\n" +
                
                "Given his ever-vigilant protection of the ordered cosmos of pre-Christian northern Europe against the forces of chaos, destruction, and entropy represented by the giants, it’s somewhat ironic that Thor is himself three-quarters giant. His father, Odin, is half-giant, and his mother, variously named as Jord (Old Norse “Earth”), Hlöðyn, or Fjörgyn, is entirely of giant ancestry." +
                " However, such a lineage is very common amongst the gods, and shows how the relationship between the gods and the giants, as tense and full of strife as it is, can’t be reduced to just enmity."));

        godsArrayList.add(new NorseGods("Loki", "The trickster of the gods. (Aesir)", "Loki, in Norse mythology, a cunning trickster who had the ability to change his shape and sex. Although his father was the giant Fárbauti, he was included among the Aesir (a tribe of gods). Loki was represented as the companion of the great gods Odin and Thor, helping them with his clever plans but sometimes causing embarrassment and difficulty for them and himself. He also appeared as the enemy of the gods, entering their banquet uninvited and demanding their drink. He was the principal cause of the death of the god Balder. Loki was bound to a rock (by the entrails of one or more of his sons, according to some sources) as punishment, thus in many ways resembling the Greek figures Prometheus and Tantalus. " +
                "Also like Prometheus, Loki is considered a god of fire. " +
                "With the female giant Angerboda (Angrboda: “Distress Bringer”), Loki produced the progeny Hel, the goddess of death; Jörmungand, the serpent that surrounds the world; and Fenrir (Fenrisúlfr), the wolf. Loki is also credited with giving birth to Sleipnir, Odin’s eight-legged horse.\n" +
                "Loki’s status in pre-Christian Scandinavia remains somewhat obscure." +
                " The medieval sources from which came much of what is known of Loki provide no evidence of a cult, unlike for other Norse deities, and the name Loki does not appear in place-names."));

        godsArrayList.add(new NorseGods("Balder", "God of beauty. (Aesir)", "Balder, Old Norse Baldr, in Norse mythology, the son of the chief god Odin and his wife Frigg. Beautiful and just, he was the favourite of the gods. Most legends about him concern his death. Icelandic stories tell how the gods amused themselves by throwing objects at him, knowing that he was immune from harm. The blind god Höd, deceived by the evil Loki, killed Balder by hurling mistletoe, the only thing that could hurt him. After Balder’s funeral, the giantess Thökk, probably Loki in disguise, refused to weep the tears that would release Balder from death."));

        godsArrayList.add(new NorseGods("Freya", " Norse goddess of love. (Aesir)", "(Old Norse: “Lady”), most renowned of the Norse goddesses, who was the sister and female counterpart of Freyr and was in charge of love, fertility, battle, and death. Her father was Njörd, the sea god. Pigs were sacred to her, and she rode a boar with golden bristles. A chariot drawn by cats was another of her vehicles. It was Freyja’s privilege to choose one-half of the heroes slain in battle for her great hall in the Fólkvangar (the god Odin took the other half to Valhalla). She possessed a famous necklace called Brísinga men, which the trickster god Loki stole and Heimdall, the gods’ watchman, recovered. Greedy and lascivious, Freyja was also credited with the evil act of teaching witchcraft to the Aesir (a tribe of gods). Like the Egyptian goddess Isis and the Greek Aphrodite, Freyja traveled through the world seeking a lost husband and weeping tears of gold. " +
                "She was also known by four nicknames—Mardöll, Hörn, Gefn, and Syr."));

        godsArrayList.add(new NorseGods("Heimdallr", "Guardian of the bridge. (Aesir)","Heimdall, Old Norse Heimdallr, in Norse mythology, the watchman of the gods. Called the shining god and whitest skinned of the gods, Heimdall dwelt at the entry to Asgard, where he guarded Bifrost, the rainbow bridge. He required less sleep than a bird, could see 100 leagues, and could hear grass growing in the meadows and wool growing on sheep. Heimdall kept the “ringing” horn, Gjallarhorn, which could be heard throughout heaven, earth, and the lower world; it was believed that he would sound the horn to summon the gods when their enemies, the giants, drew near at the Ragnarök, the end of the world of gods and men." +
                " When that time came, Heimdall and his enemy Loki would slay each other."));
        godsArrayList.add(new NorseGods("Bragi","God of eloquence. (Aesir)" , "Bragi is the son of the God Odin and the giantess Gunnlod. Bragi is very wise, and he is known for his wisdom he is very creative with words and he also has the most knowledge of poems and songs. His name Bragi means “Poet” and comes from the word “Bragr” which means “Poetry” the Vikings called their poets bragamen or bragawoman.\n" +
                
                "Bragi has a very long beard, and as strange as it sounds he has runes carved on his tongue. He is married to the beautiful Goddess of youth Iðunn, and they live together in Asgard. There have been many poets throughout the Viking age with the name Bragi, but the most famous one was Bragi Boddason who served several kings, including Ragnar Lodbrok." +
                " Bragi is recognized as the first skaldic poet, and he is certainly the earliest skaldic poet who is remembered by name whose verse survived in memory."));
        godsArrayList.add(new NorseGods("Tyr","God of war. (Aesir)","Tyr, Old Norse Týr, Old English Tiw, or Tiu, one of the oldest gods of the Germanic peoples and a somewhat enigmatic figure. He was apparently the god concerned with the formalities of war—especially treaties—and also, appropriately, of justice. It is in his character as guarantor of contracts, guardian of oaths, that the most famous myth about him may be understood: as a guarantee of good faith, he placed his hand between the jaws of the monstrous wolf Fenrir while the gods, pretending sport but intending a trap, bound the wolf; when Fenrir realized he had been tricked he bit off Tyr’s hand (hence Tyr’s identification as the one-handed god). " +
                "Tyr came to be identified by the Romans with their own Mars, hence dies Marti (Mars’ Day) came to be rendered Týsdagr (Tuesday)."));


        return godsArrayList;
    }
}
